; PlatformIO Project Configuration for EdgeAI ECG Cortex-M4
; Build command: pio run
; Output ELF: .pio/build/nucleo_f401re/firmware.elf

[platformio]
src_dir = src
include_dir = inc

[env:nucleo_f401re]
platform = ststm32
board = nucleo_f401re
framework = stm32cube
build_flags =
    -O2
    -Iinc
    -DARM_MATH_CM4
monitor_speed = 115200

[env:native]
platform = native
build_flags =
    -O2
    -Iinc
    -lm
